services:
  odoo:
    build: 
      context: .
      dockerfile: ./odoo18/Dockerfile
    depends_on:
      - postgres
    environment:
      - HOST=postgres
      - USER=odoo
      - PASSWORD=odoo
    ports:
      - "8069:8069"
      - "8072:8072" # live chat
      - "8888:8888"
    volumes:
      - odoo-data:/var/lib/odoo
      - ./extra-addons:/mnt/extra-addons
      - ./config:/etc/odoo
    networks:
      - odoo_network

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - odoo_network

networks:
  odoo_network:
    driver: bridge

volumes:
  odoo-data:
  postgres-data:
